language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
script:
  - npm test
  - npm run build
before_deploy:
  - rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: imbibe-app
  api_key:
    secure: x8GqYwOTPZCZV/pQBuWKWvfARIGJ9NW42xvktlp47QaO20q/b6q21z2BzGvUsydcYMplWVLEoNRWjbaZnJfWPhhGkvPwtoaJJPhr2vw/fNeVwgUygcgyp2IbsCiDCB4wq4R9kpEdHL4d/q1SS2IP5qX8TBmA3wuoCiwLmGMq2Ea4c9ilvZUzEp9aNuA+2Tc+ZMLH1ZlQSn5BifwCBm5q1zrvKdqbmTTKtkORNVgk2bcvH3DRswCcC54+2fRc4tBWOr+WLqHvHygn3PpHQZ2rmq2IZYELAl2rYZGzkzYFNlbxhG8LVgDmWuww5hZEdlGM6Rnh1TGh38cGjPV2RPBfdlyPMXMoBmU8AozgU46vlaeo4FyrG52t7f5QQdwFphL+G+Uwm+8/RxFr+eVZFbt7ZU9xCeH6tgAZbzS9kyfQpq4v/rkN1vOUgsk3lZtdWP3MbllQMciK1I4TzVJFtYrKuGqx/Dl7nLFRLkgUZsSYRyKGe4b31c2Zltde+sUaqRSpId4TWzCfm4coLY/4MbkQ8N89MhUq02Z7PEbPYnx0DoYbLaBn+baqxrKxSiUFP3jJQeHX/dq/SzGBnYR7pEM4Q2MlynvOIAcDipqU3aY2YcFFlYbw2dcnjrs+VRbiq8RCIDWi8sYwBKFJ1Aee/sCZsplaT2NJWp17oUkLx2Mcm7o=
